# Generated by Django 4.1.3 on 2023-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(default="", max_length=255)),
                ("Year", models.CharField(default="", max_length=4)),
                ("Rated", models.CharField(default="", max_length=10)),
                ("Released", models.CharField(default="", max_length=20)),
                ("Runtime", models.CharField(default="", max_length=10)),
                ("Genre", models.CharField(default="", max_length=255)),
                ("Director", models.CharField(default="", max_length=255)),
                ("Writer", models.CharField(default="", max_length=255)),
                ("Actors", models.CharField(default="", max_length=255)),
                ("Plot", models.TextField(default="")),
                ("Language", models.CharField(default="", max_length=50)),
                ("Country", models.CharField(default="", max_length=50)),
                ("Awards", models.CharField(default="", max_length=255)),
                ("Poster", models.TextField(default="")),
                ("Metascore", models.CharField(default="", max_length=5)),
                ("imdbRating", models.CharField(default="", max_length=5)),
                ("imdbVotes", models.CharField(default="", max_length=20)),
                ("imdbID", models.CharField(default="", max_length=20)),
                ("Type", models.CharField(default="", max_length=20)),
                ("DVD", models.CharField(default="", max_length=20)),
                ("BoxOffice", models.CharField(default="", max_length=20)),
                ("Production", models.CharField(default="", max_length=255)),
                ("Website", models.CharField(default="", max_length=255)),
                ("Response", models.CharField(default="", max_length=10)),
                ("Ratings", models.JSONField(default=list)),
                ("userIP", models.CharField(default="", max_length=20)),
            ],
        ),
    ]
